name: Download and Extract F-Droid Index

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间的凌晨 0 点触发
  workflow_dispatch: # 手动触发工作流
  push: # 当代码推送到仓库时触发

jobs:
  download-and-extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download F-Droid Index
        run: |
          curl -o index.jar https://f-droid.org/repo/index.jar

      - name: Extract index.xml from JAR
        run: |
          unzip -o index.jar index.xml

      - name: Convert index.xml to JSON
        run: |
          sudo apt-get install -y xmlstarlet
          xmlstarlet sel -t -m "/fd-index/application" -v "concat(packageName,'|',name,'|',desc,'|',versions/version/versionCode,'|',versions/version/versionName,'|',versions/version/apkName)" -n index.xml > index.txt
          # 将XML转换成JSON格式
          jq -R -s -c 'split("\n") | map(split("|") | {packageName: .[0], name: .[1], desc: .[2], versionCode: .[3], versionName: .[4], apkName: .[5]})' index.txt > index.json

      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add index.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update F-Droid Index"
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:refs/heads/main
          fi