name: Process F-Droid Index

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download index.jar
      run: |
        curl -L -o index.jar https://f-droid.org/repo/index.jar  # 替换为实际的下载链接

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml

    - name: Run Python script
      run: python process_index.py

    - name: Commit and push JSON
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "GitHub Actions"
        git add index.json
        git commit -m "Update F-Droid Index JSON"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}